"""Player income and fleet upkeep calculations."""
import typing

from constants import TAX_RATE, UPKEEP_COST_PER_HULL_POINT
from entities import Planet, Moon, ColonizableAsteroid, HullSize, Player


def calculate_player_income(galaxy: typing.Any, player: Player) -> float:
    """Calculates total credit income per turn generated by a player's colonies and active civilian habitats.

    Args:
        galaxy: Active Galaxy object or None.
        player (Player): Player whose income is being computed.

    Returns:
        float: Total credits generated per turn across all owned colonies and active civilian habitats.
    """
    total_income = 0.0
    if galaxy:
        from unit_components.enums import SabotageType
        for system in galaxy.systems.values():
            for hexcoord, body in system.get_all_celestial_bodies():
                if isinstance(body, (Planet, Moon, ColonizableAsteroid)):
                    base_tax = getattr(body, 'population', 0.0) * TAX_RATE
                    if getattr(body, 'owner', None) == player:
                        is_sab = False
                        if getattr(body, 'infiltrating_agents', None) and isinstance(body.infiltrating_agents, list) and len(body.infiltrating_agents) > 0:
                            if hasattr(body, 'is_sabotaged') and callable(body.is_sabotaged):
                                is_sab = bool(body.is_sabotaged(SabotageType.ECONOMY))
                        if is_sab:
                            total_income += base_tax * 0.5
                        else:
                            total_income += base_tax
                    else:
                        if getattr(body, 'infiltrating_agents', None) and isinstance(body.infiltrating_agents, list):
                            if any(getattr(a, 'owner', None) == player and getattr(a, 'active_sabotage', None) == SabotageType.ECONOMY for a in body.infiltrating_agents):
                                total_income += base_tax * 0.25

            for unit, _ in system.get_all_units():
                if getattr(unit, 'owner', None) == player:
                    hab_comp = getattr(unit, 'civilian_habitat_component', None)
                    if hab_comp and not hab_comp.is_destroyed:
                        if hasattr(hab_comp, 'is_active'):
                            if hab_comp.is_active(galaxy):
                                total_income += hab_comp.economic_bonus
                        elif hasattr(hab_comp, 'has_colonized_celestial_object_in_sector'):
                            if hab_comp.has_colonized_celestial_object_in_sector(galaxy):
                                total_income += hab_comp.economic_bonus
    return total_income


def calculate_player_upkeep(galaxy: typing.Any, player: Player) -> float:
    """Calculates total credit upkeep cost per turn for a player's active fleet.

    Args:
        galaxy: Active Galaxy object or None.
        player (Player): Player whose upkeep is being computed.

    Returns:
        float: Total upkeep cost per turn based on hull sizes of active units.
    """
    total_upkeep = 0.0
    if galaxy:
        for system_obj in galaxy.systems.values():
            for unit, _ in system_obj.get_all_units():
                if getattr(unit, 'owner', None) != player:
                    continue
                if getattr(unit, 'is_temporary', False):
                    continue
                if getattr(unit, 'hull_size', None) == HullSize.STRIKECRAFT_WING:
                    continue
                total_upkeep += getattr(unit, 'current_hull_usage', 0.0) * UPKEEP_COST_PER_HULL_POINT
    return total_upkeep
