"""Compatibility facade. Canonical entities live in the domain package; classes and counters retain identity."""
from importlib import import_module

_EXPORTS = {'logging': ('logging', None),
 'typing': ('typing', None),
 'Dict': ('typing', 'Dict'),
 'Optional': ('typing', 'Optional'),
 'Any': ('typing', 'Any'),
 'Tuple': ('typing', 'Tuple'),
 'TYPE_CHECKING': ('typing', 'TYPE_CHECKING'),
 'List': ('typing', 'List'),
 'HexCoord': ('domain.coordinates', 'HexCoord'),
 'generate_short_id': ('utils', 'generate_short_id'),
 'Position': ('geometry', 'Position'),
 'distance': ('geometry', 'distance'),
 'Vector': ('geometry', 'Vector'),
 'WHITE': ('constants', 'WHITE'),
 'YELLOW': ('constants', 'YELLOW'),
 'GREEN': ('constants', 'GREEN'),
 'PURPLE': ('constants', 'PURPLE'),
 'HULL_CAPACITIES': ('constants', 'HULL_CAPACITIES'),
 'HullSize': ('constants', 'HullSize'),
 'HIT_POINTS': ('constants', 'HIT_POINTS'),
 'StarType': ('constants', 'StarType'),
 'PlanetType': ('constants', 'PlanetType'),
 'NebulaType': ('constants', 'NebulaType'),
 'StormType': ('constants', 'StormType'),
 'NEBULA_COLORS': ('constants', 'NEBULA_COLORS'),
 'STORM_COLORS': ('constants', 'STORM_COLORS'),
 'MAX_UNIT_XP': ('constants', 'MAX_UNIT_XP'),
 'XP_WEAPON_DAMAGE_BONUS': ('constants', 'XP_WEAPON_DAMAGE_BONUS'),
 'XP_DEFENSE_BONUS': ('constants', 'XP_DEFENSE_BONUS'),
 'XP_SPEED_BONUS': ('constants', 'XP_SPEED_BONUS'),
 'XP_JUMP_RANGE_BONUS': ('constants', 'XP_JUMP_RANGE_BONUS'),
 'DEFAULT_SENSOR_SHORT_RANGE': ('constants', 'DEFAULT_SENSOR_SHORT_RANGE'),
 'STAR_HARVEST_MULTIPLIERS': ('constants', 'STAR_HARVEST_MULTIPLIERS'),
 'MINEFIELD_DEFAULT_DAMAGE': ('constants', 'MINEFIELD_DEFAULT_DAMAGE'),
 'MINEFIELD_DEFAULT_MINES': ('constants', 'MINEFIELD_DEFAULT_MINES'),
 'MINEFIELD_DETONATION_RADIUS': ('constants', 'MINEFIELD_DETONATION_RADIUS'),
 'POPULATION_PER_HABITAT': ('constants', 'POPULATION_PER_HABITAT'),
 'BASE_HABITAT_CAPACITY': ('constants', 'BASE_HABITAT_CAPACITY'),
 'STAR_RADIUS': ('constants', 'STAR_RADIUS'),
 'PLANET_RADIUS': ('constants', 'PLANET_RADIUS'),
 'MOON_RADIUS': ('constants', 'MOON_RADIUS'),
 'ASTEROID_RADIUS': ('constants', 'ASTEROID_RADIUS'),
 'COMET_RADIUS': ('constants', 'COMET_RADIUS'),
 'NEBULA_RADIUS': ('constants', 'NEBULA_RADIUS'),
 'CELESTIAL_FIELD_RADIUS': ('constants', 'CELESTIAL_FIELD_RADIUS'),
 'ASTEROID_FIELD_RADIUS': ('constants', 'ASTEROID_FIELD_RADIUS'),
 'ICE_FIELD_RADIUS': ('constants', 'ICE_FIELD_RADIUS'),
 'DEBRIS_FIELD_RADIUS': ('constants', 'DEBRIS_FIELD_RADIUS'),
 'STORM_RADIUS': ('constants', 'STORM_RADIUS'),
 'PLANET_TRAITS': ('constants', 'PLANET_TRAITS'),
 'HYDROGEN_NEBULA_HARVEST_MULTIPLIER': ('constants', 'HYDROGEN_NEBULA_HARVEST_MULTIPLIER'),
 'BLACK_HOLE_INHIBITION_RADIUS': ('constants', 'BLACK_HOLE_INHIBITION_RADIUS'),
 'GIANT_STAR_RADIUS': ('constants', 'GIANT_STAR_RADIUS'),
 'GIANT_STAR_INHIBITION_RADIUS': ('constants', 'GIANT_STAR_INHIBITION_RADIUS'),
 'ASTEROID_FIELD_SPEED_MOD': ('constants', 'ASTEROID_FIELD_SPEED_MOD'),
 'ICE_FIELD_SPEED_MOD': ('constants', 'ICE_FIELD_SPEED_MOD'),
 'ICE_FIELD_BEAM_DEFENSE_BONUS': ('constants', 'ICE_FIELD_BEAM_DEFENSE_BONUS'),
 'ICE_FIELD_COOLDOWN_REDUCTION': ('constants', 'ICE_FIELD_COOLDOWN_REDUCTION'),
 'DEBRIS_FIELD_SPEED_MOD': ('constants', 'DEBRIS_FIELD_SPEED_MOD'),
 'DEBRIS_FIELD_DEFENSE_BONUS': ('constants', 'DEBRIS_FIELD_DEFENSE_BONUS'),
 'DEBRIS_FIELD_HAZARD_SPEED_THRESHOLD': ('constants', 'DEBRIS_FIELD_HAZARD_SPEED_THRESHOLD'),
 'DEBRIS_FIELD_HAZARD_DAMAGE': ('constants', 'DEBRIS_FIELD_HAZARD_DAMAGE'),
 'FieldDensity': ('constants', 'FieldDensity'),
 'FIELD_DENSITY_MAX_HULL': ('constants', 'FIELD_DENSITY_MAX_HULL'),
 'FIELD_DENSITY_PARTICLES': ('constants', 'FIELD_DENSITY_PARTICLES'),
 'ASTEROID_FIELD_DENSITY_SPEED_MOD': ('constants', 'ASTEROID_FIELD_DENSITY_SPEED_MOD'),
 'ICE_FIELD_DENSITY_SPEED_MOD': ('constants', 'ICE_FIELD_DENSITY_SPEED_MOD'),
 'ICE_FIELD_DENSITY_BEAM_DEFENSE_BONUS': ('constants', 'ICE_FIELD_DENSITY_BEAM_DEFENSE_BONUS'),
 'DEBRIS_FIELD_DENSITY_SPEED_MOD': ('constants', 'DEBRIS_FIELD_DENSITY_SPEED_MOD'),
 'DEBRIS_FIELD_DENSITY_DEFENSE_BONUS': ('constants', 'DEBRIS_FIELD_DENSITY_DEFENSE_BONUS'),
 'DEBRIS_FIELD_DENSITY_HAZARD_DAMAGE': ('constants', 'DEBRIS_FIELD_DENSITY_HAZARD_DAMAGE'),
 'uuid': ('uuid', None),
 'datetime': ('datetime', 'datetime'),
 'timezone': ('datetime', 'timezone'),
 'dataclasses': ('dataclasses', None),
 'Enum': ('enum', 'Enum'),
 'auto': ('enum', 'auto'),
 'deque': ('collections', 'deque'),
 'DEFAULT_REASONING_EFFORT': ('game_ai.runtime', 'DEFAULT_REASONING_EFFORT'),
 'DEFAULT_REPAIR_RETRIES': ('game_ai.runtime', 'DEFAULT_REPAIR_RETRIES'),
 'normalize_reasoning_effort': ('game_ai.runtime', 'normalize_reasoning_effort'),
 'normalize_repair_retries': ('game_ai.runtime', 'normalize_repair_retries'),
 'PlayerController': ('player_controller', 'PlayerController'),
 'Order': ('unit_orders', 'Order'),
 'OrderStatus': ('unit_orders', 'OrderStatus'),
 'OrderType': ('unit_orders', 'OrderType'),
 'MoveOrder': ('unit_orders', 'MoveOrder'),
 'ReachWaypointOrder': ('unit_orders', 'ReachWaypointOrder'),
 'AttackOrder': ('unit_orders', 'AttackOrder'),
 'ColonizeOrder': ('unit_orders', 'ColonizeOrder'),
 'LoadColonistsOrder': ('unit_orders', 'LoadColonistsOrder'),
 'ConstructOrder': ('unit_orders', 'ConstructOrder'),
 'ToggleInhibitorOrder': ('unit_orders', 'ToggleInhibitorOrder'),
 'PatrolOrder': ('unit_orders', 'PatrolOrder'),
 'RepairOrder': ('unit_orders', 'RepairOrder'),
 'MineOrder': ('unit_orders', 'MineOrder'),
 'UnloadResourcesOrder': ('unit_orders', 'UnloadResourcesOrder'),
 'DockOrder': ('unit_orders', 'DockOrder'),
 'DeployUnitOrder': ('unit_orders', 'DeployUnitOrder'),
 'UseAbilityOrder': ('unit_orders', 'UseAbilityOrder'),
 'ProtectOrder': ('unit_orders', 'ProtectOrder'),
 'ContinuousMineOrder': ('unit_orders', 'ContinuousMineOrder'),
 'TransferAntimatterOrder': ('unit_orders', 'TransferAntimatterOrder'),
 'ContinuousResupplyOrder': ('unit_orders', 'ContinuousResupplyOrder'),
 'UnitComponent': ('unit_components', 'UnitComponent'),
 'AntimatterStorage': ('unit_components', 'AntimatterStorage'),
 'AntimatterHarvester': ('unit_components', 'AntimatterHarvester'),
 'Engines': ('unit_components', 'Engines'),
 'Hyperdrive': ('unit_components', 'Hyperdrive'),
 'HyperdriveType': ('unit_components', 'HyperdriveType'),
 'Commander': ('unit_components', 'Commander'),
 'HyperspaceInhibitionFieldEmitter': ('unit_components', 'HyperspaceInhibitionFieldEmitter'),
 'Weapons': ('unit_components', 'Weapons'),
 'Defenses': ('unit_components', 'Defenses'),
 'TurretType': ('unit_components', 'TurretType'),
 'ColonyComponent': ('unit_components', 'ColonyComponent'),
 'CivilianHabitatComponent': ('unit_components', 'CivilianHabitatComponent'),
 'OrbitalDefenseComponent': ('unit_components', 'OrbitalDefenseComponent'),
 'TradeComponent': ('unit_components', 'TradeComponent'),
 'Constructor': ('unit_components', 'Constructor'),
 'RepairComponent': ('unit_components', 'RepairComponent'),
 'MiningComponent': ('unit_components', 'MiningComponent'),
 'MetalRefineryComponent': ('unit_components', 'MetalRefineryComponent'),
 'CrystalRefineryComponent': ('unit_components', 'CrystalRefineryComponent'),
 'HangarComponent': ('unit_components', 'HangarComponent'),
 'AbilityComponent': ('unit_components', 'AbilityComponent'),
 'AbilityType': ('unit_components', 'AbilityType'),
 'StrikecraftBayComponent': ('unit_components', 'StrikecraftBayComponent'),
 'StrikecraftWingComponent': ('unit_components', 'StrikecraftWingComponent'),
 'Sensors': ('unit_components', 'Sensors'),
 'MinefieldType': ('unit_components', 'MinefieldType'),
 'MarinesComponent': ('unit_components', 'MarinesComponent'),
 'IntelligenceComponent': ('unit_components', 'IntelligenceComponent'),
 'Agent': ('unit_components', 'Agent'),
 'SabotageType': ('unit_components', 'SabotageType'),
 'CloakingDevice': ('unit_components.cloaking', 'CloakingDevice'),
 'Message': ('domain.communications', 'Message'),
 'Conversation': ('domain.communications', 'Conversation'),
 'Player': ('domain.players', 'Player'),
 'are_allies': ('domain.players', 'are_allies'),
 'are_enemies': ('domain.players', 'are_enemies'),
 'GameObject': ('domain.identity', 'GameObject'),
 '_normalize_sabotage_type': ('domain.celestials', '_normalize_sabotage_type'),
 'CelestialBody': ('domain.celestials', 'CelestialBody'),
 'Wormhole': ('domain.celestials', 'Wormhole'),
 'Star': ('domain.celestials', 'Star'),
 'Planet': ('domain.celestials', 'Planet'),
 'Moon': ('domain.celestials', 'Moon'),
 'ColonizableAsteroid': ('domain.celestials', 'ColonizableAsteroid'),
 'MetalAsteroid': ('domain.celestials', 'MetalAsteroid'),
 'DebrisField': ('domain.celestials', 'DebrisField'),
 'AsteroidField': ('domain.celestials', 'AsteroidField'),
 'IceField': ('domain.celestials', 'IceField'),
 'Nebula': ('domain.celestials', 'Nebula'),
 'Storm': ('domain.celestials', 'Storm'),
 'Comet': ('domain.celestials', 'Comet'),
 'is_position_in_magnetic_storm': ('domain.celestials', 'is_position_in_magnetic_storm'),
 'is_position_blocked_by_celestial_field': ('domain.celestials',
                                            'is_position_blocked_by_celestial_field'),
 'Minefield': ('domain.minefields', 'Minefield'),
 'Unit': ('domain.units', 'Unit'),
 'NON_SOLID_CELESTIAL_BODIES': ('domain.celestials', 'NON_SOLID_CELESTIAL_BODIES')}
__all__ = list(_EXPORTS)


def __getattr__(name):
    if name not in _EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module, attribute = _EXPORTS[name]
    value = import_module(module)
    if attribute is not None:
        value = getattr(value, attribute)
    globals()[name] = value
    return value


def __dir__():
    return sorted(set(globals()) | set(__all__))
